import { spawn } from 'node:child_process';
import net from 'node:net';
import { findRemoteFreePort, runSsh } from './ssh.mjs';

const DEFAULT_PROXY_HOST = process.env.DSH_LOCAL_PROXY_HOST || '127.0.0.1';
const DEFAULT_PROXY_PORT = Number(process.env.DSH_LOCAL_PROXY_PORT || 7890);

function safeInstanceId(value) {
  return String(value).replace(/[^A-Za-z0-9._-]/gu, '_');
}

function shellQuote(value) {
  return `'${String(value).replaceAll("'", "'\"'\"'")}'`;
}

export function probeLocalHttpProxy(host = DEFAULT_PROXY_HOST, port = DEFAULT_PROXY_PORT, timeoutMs = 3500) {
  return new Promise((resolve) => {
    const socket = net.createConnection({ host, port });
    let data = '';
    let settled = false;
    const finish = (ok, detail = '') => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      socket.destroy();
      resolve({ ok, host, port, protocol: ok ? 'http' : undefined, detail });
    };
    const timer = setTimeout(() => finish(false, 'timeout'), timeoutMs);
    socket.setEncoding('utf8');
    socket.once('error', (error) => finish(false, error.message));
    socket.once('connect', () => {
      socket.write('CONNECT github.com:443 HTTP/1.1\r\nHost: github.com:443\r\nProxy-Connection: keep-alive\r\n\r\n');
    });
    socket.on('data', (chunk) => {
      data += chunk;
      const firstLine = data.split(/\r?\n/u)[0] || '';
      if (/^HTTP\/1\.[01] 2\d\d\b/u.test(firstLine)) finish(true, firstLine);
      else if (/^HTTP\/1\.[01] \d{3}\b/u.test(firstLine)) finish(false, firstLine);
    });
  });
}

async function writeRemoteProxyEnvironment(host, instanceId, proxyUrl) {
  const safeId = safeInstanceId(instanceId);
  const quotedProxy = shellQuote(proxyUrl);
  const script = `set -e\nROOT="\${DEEPSEEK_HARNESS_REMOTE_HOME:-$HOME/.deepseek-harness-remote}"\nDIR="$ROOT/session-env"\nmkdir -p "$DIR"\ncat > "$DIR/network-${safeId}.sh" <<'EOF'\n# Generated by DeepSeek Harness Remote. Bash/tool traffic only.\nexport HTTP_PROXY=${quotedProxy}\nexport HTTPS_PROXY=${quotedProxy}\nexport ALL_PROXY=${quotedProxy}\nexport http_proxy=${quotedProxy}\nexport https_proxy=${quotedProxy}\nexport all_proxy=${quotedProxy}\nexport NO_PROXY='api.deepseek.com,.deepseek.com,127.0.0.1,localhost,::1'\nexport no_proxy="$NO_PROXY"\nEOF\nchmod 600 "$DIR/network-${safeId}.sh"\n`;
  await runSsh(host, script, { timeoutMs: 15000 });
}

export async function clearRemoteProxyEnvironment(host, instanceId) {
  const safeId = safeInstanceId(instanceId);
  await runSsh(host, `ROOT="\${DEEPSEEK_HARNESS_REMOTE_HOME:-$HOME/.deepseek-harness-remote}"\nrm -f "$ROOT/session-env/network-${safeId}.sh"\n`, { timeoutMs: 10000 }).catch(() => undefined);
}

export async function startLocalProxyBridge({ host, instanceId, runtimeBin, onLog, localProxyHost = DEFAULT_PROXY_HOST, localProxyPort = DEFAULT_PROXY_PORT } = {}) {
  const probe = await probeLocalHttpProxy(localProxyHost, localProxyPort);
  if (!probe.ok) {
    onLog?.(`[network] Local proxy ${localProxyHost}:${localProxyPort} is unavailable (${probe.detail || 'probe failed'}); remote Bash traffic will use the server network directly.\n`);
    return { enabled: false, localProxyHost, localProxyPort };
  }

  const remoteProxyPort = await findRemoteFreePort(host, runtimeBin);
  const args = [
    '-o', 'BatchMode=yes',
    '-o', 'ConnectTimeout=10',
    '-o', 'ServerAliveInterval=20',
    '-o', 'ServerAliveCountMax=3',
    '-o', 'StrictHostKeyChecking=accept-new',
    '-T',
    '-N',
    '-o', 'ExitOnForwardFailure=no',
    '-R', `${remoteProxyPort}:${localProxyHost}:${localProxyPort}`,
    host,
  ];
  const child = spawn('ssh', args, { windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  child.stdout?.setEncoding('utf8');
  child.stderr?.setEncoding('utf8');
  child.stdout?.on('data', (chunk) => onLog?.(`[network:ssh] ${String(chunk)}`));
  child.stderr?.on('data', (chunk) => onLog?.(`[network:ssh] ${String(chunk)}`));

  await new Promise((resolve, reject) => {
    let settled = false;
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      resolve();
    }, 900);
    child.once('error', (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(error);
    });
    child.once('exit', (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(new Error(`Proxy SSH bridge exited early with code ${code}.`));
    });
  });

  const proxyUrl = `http://127.0.0.1:${remoteProxyPort}`;
  await writeRemoteProxyEnvironment(host, instanceId, proxyUrl);
  onLog?.(`[network] Bash/Git/web traffic will use local proxy ${localProxyHost}:${localProxyPort} through SSH reverse port ${remoteProxyPort}.\n`);
  onLog?.('[network] DeepSeek model traffic is NOT given HTTP_PROXY/HTTPS_PROXY and remains on the remote server network.\n');
  return {
    enabled: true,
    mode: 'local-proxy',
    localProxyHost,
    localProxyPort,
    remoteProxyPort,
    proxyUrl,
    child,
  };
}
